builds:
  - name: Nodewatch
    path: explorer/nodewatch

  - name: Light API Python
    path: lightapi/python

  - name: Optin Puller
    path: optin/puller

  - name: Optin Reporting
    path: optin/reporting

  - name: Shoestring
    path: tools/shoestring

  - name: Vanity Address Generator
    path: tools/vanity

customBuilds:
  - name: Nightly Job
    jobName: nightlyJob
    scriptPath: .github/jenkinsfile/nightlyBuild.groovy
    triggers:
      - type: cron
        schedule: '@midnight'
